CREATE TABLE IF NOT EXISTS `DEPARTMENT`` (
  `ID` varchar(5) DEFAULT "-",
  `NAME` varchar(20) DEFAULT "-",
  `LOCATION` varchar(20) DEFAULT "-",
  `MANAGER_FK_ID` varchar(6) DEFAULT "-",
  `UPDATED_BY` varchar(10) DEFAULT "-",
  `UPDATED_ON` date DEFAULT GETDATE(),
  PRIMARY KEY (`ID`),
  CONSTRAINT FK_EMPLOYEE FOREIGN KEY (MANAGER_FK_ID) REFERENCES EMPLOYEE(ID)
);

CREATE TABLE IF NOT EXISTS `EMPLOYEE` (
  `ID` varchar(6) DEFAULT "-",
  `NAME` varchar(100) DEFAULT "-",
  `DESIGNATION` varchar(50) DEFAULT "-",
  `SALARY` float DEFAULT 0.00,
  `EMAIL` varchar(50) DEFAULT "-",
  `DOB` date DEFAULT "-",
  `GENDER` varchar(1) DEFAULT "-",
  `ADDRESS` varchar(300) DEFAULT "-",
  `MOBILE_NO` varchar(10) DEFAULT "-",
  `OTHER_NO` varchar(10) DEFAULT "-",
  `DEPT_FK_ID` varchar(5) DEFAULT "-",
  `DATE_OF_JOIN` date DEFAULT "-",
  `UPDATED_BY` varchar(10) DEFAULT "-",
  `UPDATED_ON` date DEFAULT GETDATE(),
  PRIMARY KEY (`ID`),
  CONSTRAINT FK_DEPARTMENT FOREIGN KEY (DEPT_FK_ID) REFERENCES DEPARTMENT(ID)
);

CREATE TABLE IF NOT EXISTS `DEPENDENT` (
  `ID` varchar(5) DEFAULT "-",
  `NAME` varchar(100) DEFAULT "-",
  `DOB` date DEFAULT GETDATE(),
  `EMPLOYEE_FK_ID` varchar(6) DEFAULT "-",
  `UPDATED_BY` varchar(10) DEFAULT "-",
  `UPDATED_ON` date DEFAULT GETDATE(),
  PRIMARY KEY (`ID`),
  CONSTRAINT FK_DEPARTMENT FOREIGN KEY (EMPLOYEE_FK_ID) REFERENCES EMPLOYEE(ID)
);