/*
*20160424 PN hra.master.ddl.sql V02 created.
*20160504 PN Tables modified with DEFAULT CONSTRAINT.
*
*/

CREATE TABLE [HRA.EMPLOYEE] (
ID INT NOT NULL IDENTITY (1,1),
NAME varchar(300) NOT NULL CONSTRAINT DF_NAME_EMPLOYEE DEFAULT ('-') ,
DESIGNATION varchar(50) NOT NULL CONSTRAINT DF_DESIGNATION_EMPLOYEE DEFAULT ('-') ,
EMAIL varchar(50) NOT NULL CONSTRAINT DF_EMAIL_EMPLOYEE DEFAULT ('-') ,
DOB date NOT NULL CONSTRAINT DF_DOB_EMPLOYEE DEFAULT (getdate()) ,
NIC varchar(15) NOT NULL CONSTRAINT DF_NIC_EMPLOYEE DEFAULT ('-') ,
GENDER varchar(1) NOT NULL CONSTRAINT DF_GENDER_EMPLOYEE DEFAULT ('-') ,
PERMENENTADDRESS varchar(300) NOT NULL CONSTRAINT DF_PERMENENTADDRESS_EMPLOYEE DEFAULT ('-') ,
TEMPORARYADDRESS varchar(300) NOT NULL CONSTRAINT DF_TEMPORARYADDRESS_EMPLOYEE DEFAULT ('-') ,
MOBILENO varchar(10) NOT NULL CONSTRAINT DF_MOBILENO_EMPLOYEE DEFAULT ('-') ,
OTHERNO varchar(10) NOT NULL CONSTRAINT DF_OTHERNO_EMPLOYEE DEFAULT ('-') ,
DEPTID varchar(5) NOT NULL CONSTRAINT DF_DEPTID_EMPLOYEE DEFAULT ('-') ,
MARITALSTATUS varchar(10) NOT NULL CONSTRAINT DF_MARITALSTATUS_EMPLOYEE DEFAULT ('-') ,
DATEOFJOIN date NOT NULL CONSTRAINT DF_DATEOFJOIN_EMPLOYEE DEFAULT (getdate()) ,
MODBY varchar(10) NOT NULL CONSTRAINT DF_MODBY_EMPLOYEE DEFAULT ('-') ,
MODON date NOT NULL CONSTRAINT DF_MODON_EMPLOYEE DEFAULT (getdate()) ,
EPF varchar(10) NOT NULL CONSTRAINT DF_EPF_EMPLOYEE DEFAULT ('-') ,
BASIS varchar(10) NOT NULL CONSTRAINT DF_BASIS_EMPLOYEE DEFAULT ('-'),
CONSTRAINT EMPLOYEE_ID_PK_ID PRIMARY KEY (ID),
CONSTRAINT DEPARTMENT_ID_FK_DEPTFKID FOREIGN KEY (DEPTID) REFERENCES DEPARTMENT(ID)
)
-- ----------------------------
-- Table structure for DEPARTMENT
-- ----------------------------
CREATE TABLE [HRA.DEPARTMENT] (
ID INT NOT NULL IDENTITY (1,1),
NAME varchar(20) NOT NULL CONSTRAINT DF_NAME_EMPLOYEE DEFAULT ('-') ,
LOCATION varchar(20) NOT NULL CONSTRAINT DF_LOCATION_EMPLOYEE DEFAULT ('-') ,
MANAGERID varchar(6) NOT NULL CONSTRAINT DF_MANAGERID_EMPLOYEE DEFAULT ('-') ,
MODBY varchar(10) NOT NULL CONSTRAINT DF_MODBY_EMPLOYEE DEFAULT ('-') ,
MODON date NOT NULL CONSTRAINT DF_MODON_EMPLOYEE DEFAULT ('-') ,
CONSTRAINT DEPARTMENT_ID_PK_ID PRIMARY KEY (ID),
CONSTRAINT EMPLOYEE_ID_FK_MANAGERFKID FOREIGN KEY (MANAGERID) REFERENCES EMPLOYEE(ID)
)

-- ----------------------------
-- Table structure for EMPLOYMENTHISTORY
-- ----------------------------
CREATE TABLE [HRA.EMPLOYMENTHISTORY] (
  ID INT NOT NULL IDENTITY (1,1),
  EMPLOYEEID varchar(10) NOT NULL CONSTRAINT DF_EMPLOYEEID_EMPLOYMENTHISTORY DEFAULT ('-') ,
  EMPLOYERNAME varchar(100) NOT NULL CONSTRAINT DF_EMPLOYERNAME_EMPLOYMENTHISTORY DEFAULT ('-') ,
  DESIGNATION varchar(20) NOT NULL CONSTRAINT DF_NAME_EMPLOYMENTHISTORY DEFAULT ('-') ,
  STARTDATE date NOT NULL CONSTRAINT DF_DESIGNATION_EMPLOYMENTHISTORY DEFAULT (getdate()) ,
  ENDDATE date NOT NULL CONSTRAINT DF_ENDDATE_EMPLOYMENTHISTORY DEFAULT (getdate()) ,
  BASIS varchar(10) NOT NULL CONSTRAINT DF_BASIS_EMPLOYMENTHISTORY DEFAULT ('-') ,
  COMMENTS varchar(200) NOT NULL CONSTRAINT DF_COMMENTS_EMPLOYMENTHISTORY DEFAULT ('-') ,
  REFERENCENAME varchar(300) NOT NULL CONSTRAINT DF_REFERENCENAME_EMPLOYMENTHISTORY DEFAULT ('-') ,
  REFERENCEPHONE varchar(30) NOT NULL CONSTRAINT DF_REFERENCEPHONE_EMPLOYMENTHISTORY DEFAULT ('-') ,
  REFERENCEMOBILE varchar(30) NOT NULL CONSTRAINT DF_REFERENCEMOBILE_EMPLOYMENTHISTORY DEFAULT ('-') ,
  REFERENCEADDRESS varchar(500) NOT NULL CONSTRAINT DF_REFERENCEADDRESS_EMPLOYMENTHISTORY DEFAULT ('-') ,
  REFERENCEDESIGNATION varchar(100) NOT NULL CONSTRAINT DF_REFERENCEDESIGNATION_EMPLOYMENTHISTORY DEFAULT ('-') ,
  REFERENCECOMMENTS varchar(300) NOT NULL CONSTRAINT DF_REFERENCECOMMENTS_EMPLOYMENTHISTORY DEFAULT ('-') ,
  MODBY date NOT NULL CONSTRAINT DF_MODBY_EMPLOYMENTHISTORY DEFAULT (getdate()) ,
  MODON date NOT NULL CONSTRAINT DF_MODON_EMPLOYMENTHISTORY DEFAULT (getdate()) ,
  CONSTRAINT EMPLOYMENTHISTORY_ID_PK_ID PRIMARY KEY (ID),
  CONSTRAINT EMPLOYEE_ID_FK_MANAGERFKID FOREIGN KEY (EMPLOYEEID) REFERENCES EMPLOYEE(ID)
)

-- ----------------------------
-- Table structure for FAMILY
-- ----------------------------
CREATE TABLE [HRA.FAMILY] (
  ID INT NOT NULL IDENTITY (1,1),
  EMPLOYEEID varchar(10) NOT NULL CONSTRAINT DF_EMPLOYEEID_FAMILY DEFAULT ('-') ,
  NAME varchar(200) NOT NULL CONSTRAINT DF_NAME_FAMILY DEFAULT ('-') ,
  DATEOFBIRTH date NOT NULL CONSTRAINT DF_DATEOFBIRTH_FAMILY DEFAULT (getdate()) ,
  RELATIONSHIP varchar(10) NOT NULL CONSTRAINT DF_RELATIONSHIP_FAMILY DEFAULT ('-') ,
  OCCUPATION varchar(20) NOT NULL CONSTRAINT DF_OCCUPATION_FAMILY DEFAULT ('-') ,
  PLACE varchar(200) NOT NULL CONSTRAINT DF_PLACE_FAMILY DEFAULT ('-') ,
  MODBY date NOT NULL CONSTRAINT DF_MODBY_FAMILY DEFAULT (getdate()) ,
  MODON date NOT NULL CONSTRAINT DF_MODON_FAMILY DEFAULT (getdate()) ,
  CONSTRAINT FAMILY_ID_PK_ID PRIMARY KEY (ID),
  CONSTRAINT EMPLOYEE_ID_FK_MANAGERFKID FOREIGN KEY (EMPLOYEEID) REFERENCES EMPLOYEE(ID)
) 

-- ----------------------------
-- Table structure for LOAN
-- ----------------------------
CREATE TABLE [HRA.LOAN] (
  ID INT NOT NULL IDENTITY (1,1),
  EMPLOYEEID varchar(10) NOT NULL CONSTRAINT DF_EMPLOYEEID_LOAN DEFAULT ('-') ,
  DUEDATE date NOT NULL CONSTRAINT DF_DUEDATE_LOAN DEFAULT (getdate()) ,
  TOTALOUTSTANDING double NOT NULL CONSTRAINT DF_TOTALOUTSTANDING_LOAN DEFAULT ('0') ,
  BORROWER varchar(200) NOT NULL CONSTRAINT DF_BORROWER_LOAN DEFAULT ('-') ,
  MONTHLYPAYMENT double NOT NULL CONSTRAINT DF_MONTHLYPAYMENT_LOAN DEFAULT ('0') ,
  MODBY date NOT NULL CONSTRAINT DF_MODBY_LOAN DEFAULT (getdate()) ,
  MODON date NOT NULL CONSTRAINT DF_MODON_LOAN DEFAULT (getdate()) ,
  CONSTRAINT LOAN_ID_PK_ID PRIMARY KEY (ID),
  CONSTRAINT EMPLOYEE_ID_FK_MANAGERFKID FOREIGN KEY (EMPLOYEEID) REFERENCES EMPLOYEE(ID)
) 

-- ----------------------------
-- Table structure for QUALIFICATION
-- ----------------------------
CREATE TABLE [HRA.QUALIFICATION] (
  ID INT NOT NULL IDENTITY (1,1),
  EMPLOYEEID varchar(10) NOT NULL CONSTRAINT DF_EMPLOYEEID_QUALIFICATION DEFAULT ('-') ,
  STUDYPLACE varchar(100) NOT NULL CONSTRAINT DF_STUDYPLACE_QUALIFICATION DEFAULT ('-') ,
  ADDMISSIONYEAR int(11) DEFAULT NOT NULL,
  QUALIFICATION varchar(200) NOT NULL CONSTRAINT DF_QUALIFICATION_QUALIFICATION DEFAULT ('-') ,
  MEDIUM varchar(10) NOT NULL CONSTRAINT DF_MEDIUM_QUALIFICATION DEFAULT ('-') ,
  LEAVINGDATE date DEFAULT GETDATE(),
  MODBY date NOT NULL CONSTRAINT DF_MODBY_QUALIFICATION DEFAULT (getdate()) ,
  MODON date NOT NULL CONSTRAINT DF_MODON_QUALIFICATION DEFAULT (getdate()) ,
  CONSTRAINT QUALIFICATION_ID_PK_ID PRIMARY KEY (ID),
  CONSTRAINT EMPLOYEE_ID_FK_MANAGERFKID FOREIGN KEY (EMPLOYEEID) REFERENCES EMPLOYEE(ID)
) 

-- ----------------------------
-- Table structure for STUDYPROGRAM
-- ----------------------------
CREATE TABLE [HRA.STUDYPROGRAM] (
  ID INT NOT NULL IDENTITY (1,1),
  EMPLOYEEID varchar(10) NOT NULL CONSTRAINT DF_EMPLOYEEID_STUDYPROGRAM DEFAULT ('-') ,
  TIMEPERIOD varchar(10) NOT NULL CONSTRAINT DF_TIMEPERIOD_STUDYPROGRAM DEFAULT ('-') ,
  INSTITUTION varchar(200) NOT NULL CONSTRAINT DF_INSTITUTION_STUDYPROGRAM DEFAULT ('-') ,
  COURSETYPE varchar(50) DNULL CONSTRAINT DF_COURSETYPE_STUDYPROGRAM DEFAULT ('-') ,
  ADDMISIONDATE date NOT NULL CONSTRAINT DF_ADDMISIONDATE_STUDYPROGRAM DEFAULT (getdate()) ,
  DURATION int(11) DEFAULT '0',
  MODBY date NOT NULL CONSTRAINT DF_MODBY_STUDYPROGRAM DEFAULT (getdate()) ,
  MODON date NOT NULL CONSTRAINT DF_MODON_STUDYPROGRAM DEFAULT (getdate()) ,
  CONSTRAINT STUDYPROGRAM_ID_PK_ID PRIMARY KEY (ID),
  CONSTRAINT EMPLOYEE_ID_FK_MANAGERFKID FOREIGN KEY (EMPLOYEEID) REFERENCES EMPLOYEE(ID)
) 
