CREATE TABLE IF NOT EXISTS `DEPARTMENT`` (
  `ID` varchar(5) DEFAULT "-",
  `NAME` varchar(20) DEFAULT "-",
  `LOCATION` varchar(20) DEFAULT "-",
  `MANAGERID` varchar(6) DEFAULT "-",
  `MODBY` varchar(10) DEFAULT "-",
  `MODON` date DEFAULT GETDATE(),
  CONSTRAINT DEPARTMENT_ID_PK_ID PRIMARY KEY (DEPTFKID) REFERENCES DEPARTMENT(ID),
  CONSTRAINT EMPLOYEE_ID_FK_MANAGERFKID FOREIGN KEY (MANAGERID) REFERENCES EMPLOYEE(ID)
);

CREATE TABLE IF NOT EXISTS `EMPLOYEE` (
  `ID` varchar(6) DEFAULT "-",
  `NAME` varchar(100) DEFAULT "-",
  `DESIGNATION` varchar(50) DEFAULT "-",
  `SALARY` float DEFAULT 0.00,
  `EMAIL` varchar(50) DEFAULT "-",
  `DOB` date DEFAULT "-",
  `NIC` date DEFAULT "-",
  `GENDER` varchar(1) DEFAULT "-",
  `ADDRESS` varchar(300) DEFAULT "-",
  `MOBILENO` varchar(10) DEFAULT "-",
  `OTHERNO` varchar(10) DEFAULT "-",
  `DEPTID` varchar(5) DEFAULT "-",
  `DATEOFJOIN` date DEFAULT "-",
  `MODBY` date DEFAULT GETDATE(),
  `MODON` date DEFAULT GETDATE(),
  CONSTRAINT EMPLOYEE_ID_PK_ID PRIMARY KEY (DEPTID) REFERENCES DEPARTMENT(ID),
  CONSTRAINT DEPARTMENT_ID_FK_DEPTFKID FOREIGN KEY (DEPTFKID) REFERENCES DEPARTMENT(ID)
);

CREATE TABLE IF NOT EXISTS `EMPLOYEEWORKEXPERIENCE` (
  `ID` varchar(6) DEFAULT "-",
  `WORKEDPLACE` date DEFAULT GETDATE(),
  `STARTEDDATE` date DEFAULT GETDATE(),
  `ENDDATE` date DEFAULT GETDATE(),
  `COMMENTS` varchar(200) DEFAULT "-",
  `MODBY` date DEFAULT GETDATE(),
  `MODON` date DEFAULT GETDATE(),
  CONSTRAINT EMPLOYEE_ID_FK_ID FOREIGN KEY (ID) REFERENCES EMPLOYEE(ID)
);

CREATE TABLE IF NOT EXISTS `EMPLOYEEQUALIFICATION` (
  `ID` varchar(6) DEFAULT "-",
  `COLLEGENAME`` varchar(100) DEFAULT "-",
  `EDUCATIONALYEAR` YEAR` varchar(50) DEFAULT "-",
  `QUALIFICATION` float DEFAULT 0.00,
  `COMMENTS` varchar(200) DEFAULT "-",
  `MODBY` date DEFAULT GETDATE(),
  `MODON` date DEFAULT GETDATE(),
  CONSTRAINT EMPLOYEE_ID_FK_ID FOREIGN KEY (ID) REFERENCES EMPLOYEE(ID)
);
